// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/demo/src/demo.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IconDocument: typeof import('@element-plus/icons-vue')['Document']
    IconFold: typeof import('@element-plus/icons-vue')['Fold']
    IconLocation: typeof import('@element-plus/icons-vue')['Location']
    IconMenu: typeof import('@element-plus/icons-vue')['Menu']
    IconMoon: typeof import('@element-plus/icons-vue')['Moon']
    IconSetting: typeof import('@element-plus/icons-vue')['Setting']
    IconSunny: typeof import('@element-plus/icons-vue')['Sunny']
    Lottie: typeof import('./src/components/lottie/src/lottie.vue')['default']
    MLottie: typeof import('@/components')['MLottie']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
