// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/demo/src/demo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElLink: typeof import('element-plus/es')['ElLink']
    Lottie: typeof import('./src/components/lottie/src/lottie.vue')['default']
    MDemo: typeof import('@/components')['MDemo']
    MLottie: typeof import('@/components')['MLottie']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
